### ISSUE TITLE
Compile error PIDKlin 1.3

### ISSUE THREAD

**Issue by RepRapThailand** [Saur0o0n/pidkiln#57]
[error2.txt](https://github.com/user-attachments/files/22735988/error2.txt)

Dear Sir,

Arduino\PIDKiln\PIDKiln.ino:32:10: fatal error: soc/rtc_wdt.h: No such file or directory
   32 | #include <soc/rtc_wdt.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
Alternatives for soc/rtc_wdt.h: []
ResolveLibrary(soc/rtc_wdt.h)
  -> candidates: []
exit status 1

Compilation error: soc/rtc_wdt.h: No such file or directory

compile with Auduino 2.3.6

[pidklin13.txt](https://github.com/user-attachments/files/22727514/pidklin13.txt)

ESP32 framework 3.3.1

Regards,
KK.
